DOCSP-44896 - TOC labels
mongodb/docs-visual-studio-extension pull request #68
Opened 2024-10-31 21:20 UTC by mongoKart

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-visual-studio-extension/blob/master/REVIEWING.md)

JIRA - https://jira.mongodb.org/browse/DOCSP-44896

### Staging Links

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?
- [x] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-10-31 22:28 UTC, sarahemlin approved these changes

2024-11-01 20:53 UTC, lindseymoore approved these changes
LGTM!

2024-11-01 22:33 UTC, sarahemlin requested changes

2024-11-01 22:33 UTC, sarahemlin commented on source/index.txt
> +   Rules and Message Content </rules>
@mongoKart ampersand

2024-11-07 15:00 UTC, sarahemlin approved these changes

2024-11-07 17:25 UTC, merged